-- aidev initial schema.
--
-- Design notes that are not obvious from the DDL:
--
--   * Status columns are TEXT + CHECK rather than native enum types. A CHECK
--     list can be changed by a plain migration; ALTER TYPE ... ADD VALUE is
--     more awkward to roll back and cannot be combined freely with other DDL in
--     one transaction. The allowed values mirror the Go constants exactly, and
--     unit tests read this file to assert the two never drift.
--
--   * Primary keys are UUIDs generated by the application (UUIDv7, which is
--     time-ordered, so index locality is close to that of a serial key without
--     coupling identity to a shared counter).
--
--   * tasks.ref is the human-facing identifier. It comes from a sequence so
--     that a person can type TASK-000007 instead of a UUID.
--
--   * Captured output is TEXT with a companion *_truncated flag. aidev bounds
--     output before it reaches the database, so a runaway agent cannot fill the
--     disk, and the flag makes the bound visible rather than silent.

CREATE TABLE projects (
    id              UUID        PRIMARY KEY,
    name            TEXT        NOT NULL,
    repo_path       TEXT        NOT NULL UNIQUE,
    default_branch  TEXT        NOT NULL DEFAULT 'main',
    created_at      TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at      TIMESTAMPTZ NOT NULL DEFAULT now(),

    CONSTRAINT projects_name_not_blank      CHECK (length(btrim(name)) > 0),
    CONSTRAINT projects_repo_path_absolute  CHECK (repo_path LIKE '/%'),
    CONSTRAINT projects_branch_not_blank    CHECK (length(btrim(default_branch)) > 0)
);

-- Human-facing task references: TASK-000001, TASK-000002, ...
CREATE SEQUENCE task_ref_seq AS BIGINT START WITH 1;

CREATE TABLE tasks (
    id                   UUID        PRIMARY KEY,
    ref                  TEXT        NOT NULL UNIQUE
                                     DEFAULT 'TASK-' || lpad(nextval('task_ref_seq')::text, 6, '0'),
    project_id           UUID        NOT NULL REFERENCES projects (id) ON DELETE RESTRICT,
    title                TEXT        NOT NULL,
    description          TEXT        NOT NULL DEFAULT '',
    agent                TEXT        NOT NULL,
    priority             INTEGER     NOT NULL DEFAULT 0,
    status               TEXT        NOT NULL,
    acceptance_criteria  TEXT        NOT NULL DEFAULT '',

    -- Verification steps as argv objects: [{"command":"go","args":["test","./..."]}]
    -- At least one step is required: a task aidev cannot independently verify
    -- is a task aidev will not accept.
    verification         JSONB       NOT NULL,

    max_retries          INTEGER     NOT NULL DEFAULT 0,
    requires_approval    BOOLEAN     NOT NULL DEFAULT false,
    base_ref             TEXT        NOT NULL DEFAULT '',
    timeout_seconds      INTEGER     NOT NULL DEFAULT 0,  -- 0 means "use the configured default"
    created_at           TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at           TIMESTAMPTZ NOT NULL DEFAULT now(),

    CONSTRAINT tasks_title_not_blank CHECK (length(btrim(title)) > 0),
    CONSTRAINT tasks_title_length    CHECK (length(title) <= 200),
    CONSTRAINT tasks_agent_not_blank CHECK (length(btrim(agent)) > 0),
    CONSTRAINT tasks_status_valid    CHECK (status IN (
        'PENDING', 'READY', 'RUNNING', 'VERIFYING',
        'SUCCEEDED', 'FAILED', 'CANCELLED', 'WAITING_APPROVAL')),
    CONSTRAINT tasks_priority_range  CHECK (priority BETWEEN -1000 AND 1000),
    CONSTRAINT tasks_retries_range   CHECK (max_retries BETWEEN 0 AND 10),
    CONSTRAINT tasks_timeout_range   CHECK (timeout_seconds >= 0),
    CONSTRAINT tasks_verification_is_nonempty_array CHECK (
        jsonb_typeof(verification) = 'array' AND jsonb_array_length(verification) >= 1)
);

-- Listing a project's tasks, the common read path.
CREATE INDEX tasks_project_created_idx ON tasks (project_id, created_at DESC);

-- Claiming runnable work. Shaped for the query a future scheduler needs:
--   SELECT ... WHERE status = 'READY' ORDER BY priority DESC, created_at
--   FOR UPDATE SKIP LOCKED
-- so that adding concurrent workers does not require an index change.
CREATE INDEX tasks_ready_claim_idx ON tasks (priority DESC, created_at)
    WHERE status = 'READY';

CREATE TABLE task_attempts (
    id              UUID        PRIMARY KEY,
    task_id         UUID        NOT NULL REFERENCES tasks (id) ON DELETE CASCADE,
    attempt_number  INTEGER     NOT NULL,
    status          TEXT        NOT NULL,
    failure_kind    TEXT        NOT NULL DEFAULT '',
    error           TEXT        NOT NULL DEFAULT '',
    started_at      TIMESTAMPTZ NOT NULL DEFAULT now(),
    finished_at     TIMESTAMPTZ,

    CONSTRAINT task_attempts_number_positive CHECK (attempt_number >= 1),
    CONSTRAINT task_attempts_unique_number   UNIQUE (task_id, attempt_number),
    CONSTRAINT task_attempts_status_valid    CHECK (status IN (
        'RUNNING', 'SUCCEEDED', 'FAILED', 'CANCELLED')),
    CONSTRAINT task_attempts_failure_valid   CHECK (failure_kind IN (
        '', 'STARTUP', 'AGENT_ERROR', 'AGENT_EXIT', 'TIMEOUT', 'CANCELLED',
        'VERIFICATION', 'WORKTREE', 'APPROVAL_DENIED', 'INTERNAL', 'UNKNOWN')),
    -- A finished attempt must have an outcome, and a running one must not.
    CONSTRAINT task_attempts_finished_consistent CHECK (
        (status = 'RUNNING' AND finished_at IS NULL) OR
        (status <> 'RUNNING' AND finished_at IS NOT NULL))
);

CREATE INDEX task_attempts_task_idx ON task_attempts (task_id, attempt_number DESC);

CREATE TABLE worktrees (
    id           UUID        PRIMARY KEY,
    -- One worktree per attempt: the isolation boundary is per attempt, so a
    -- second row for the same attempt would mean a bug, not a feature.
    attempt_id   UUID        NOT NULL UNIQUE REFERENCES task_attempts (id) ON DELETE CASCADE,
    path         TEXT        NOT NULL,
    branch       TEXT        NOT NULL,
    base_commit  TEXT        NOT NULL,
    head_commit  TEXT        NOT NULL DEFAULT '',
    status       TEXT        NOT NULL,
    created_at   TIMESTAMPTZ NOT NULL DEFAULT now(),
    removed_at   TIMESTAMPTZ,

    CONSTRAINT worktrees_path_absolute CHECK (path LIKE '/%'),
    CONSTRAINT worktrees_status_valid  CHECK (status IN ('ACTIVE', 'REMOVED', 'RETAINED')),
    CONSTRAINT worktrees_removed_consistent CHECK (
        (status = 'REMOVED' AND removed_at IS NOT NULL) OR
        (status <> 'REMOVED' AND removed_at IS NULL))
);

CREATE TABLE worker_runs (
    id                UUID        PRIMARY KEY,
    attempt_id        UUID        NOT NULL REFERENCES task_attempts (id) ON DELETE CASCADE,
    backend           TEXT        NOT NULL,
    status            TEXT        NOT NULL,
    failure_kind      TEXT        NOT NULL DEFAULT '',
    command           TEXT        NOT NULL,
    working_dir       TEXT        NOT NULL,
    exit_code         INTEGER,
    stdout            TEXT        NOT NULL DEFAULT '',
    stdout_truncated  BOOLEAN     NOT NULL DEFAULT false,
    stderr            TEXT        NOT NULL DEFAULT '',
    stderr_truncated  BOOLEAN     NOT NULL DEFAULT false,
    session_id        TEXT        NOT NULL DEFAULT '',
    summary           TEXT        NOT NULL DEFAULT '',
    finish_reason     TEXT        NOT NULL DEFAULT '',
    tokens            JSONB,
    cost              NUMERIC(12, 6),
    diff              TEXT        NOT NULL DEFAULT '',
    diff_truncated    BOOLEAN     NOT NULL DEFAULT false,
    changed_files     INTEGER     NOT NULL DEFAULT 0,
    started_at        TIMESTAMPTZ NOT NULL DEFAULT now(),
    finished_at       TIMESTAMPTZ,

    CONSTRAINT worker_runs_backend_not_blank CHECK (length(btrim(backend)) > 0),
    CONSTRAINT worker_runs_status_valid      CHECK (status IN (
        'SUCCEEDED', 'FAILED', 'TIMED_OUT', 'CANCELLED')),
    CONSTRAINT worker_runs_failure_valid     CHECK (failure_kind IN (
        '', 'STARTUP', 'AGENT_ERROR', 'AGENT_EXIT', 'TIMEOUT', 'CANCELLED',
        'VERIFICATION', 'WORKTREE', 'APPROVAL_DENIED', 'INTERNAL', 'UNKNOWN')),
    CONSTRAINT worker_runs_changed_files_nonneg CHECK (changed_files >= 0)
);

CREATE INDEX worker_runs_attempt_idx ON worker_runs (attempt_id, started_at);

CREATE TABLE verification_runs (
    id                UUID        PRIMARY KEY,
    attempt_id        UUID        NOT NULL REFERENCES task_attempts (id) ON DELETE CASCADE,
    step_index        INTEGER     NOT NULL,
    command           TEXT        NOT NULL,
    status            TEXT        NOT NULL,
    exit_code         INTEGER,
    stdout            TEXT        NOT NULL DEFAULT '',
    stdout_truncated  BOOLEAN     NOT NULL DEFAULT false,
    stderr            TEXT        NOT NULL DEFAULT '',
    stderr_truncated  BOOLEAN     NOT NULL DEFAULT false,
    duration_ms       BIGINT      NOT NULL DEFAULT 0,
    started_at        TIMESTAMPTZ NOT NULL DEFAULT now(),
    finished_at       TIMESTAMPTZ,

    CONSTRAINT verification_runs_step_nonneg   CHECK (step_index >= 0),
    CONSTRAINT verification_runs_unique_step   UNIQUE (attempt_id, step_index),
    CONSTRAINT verification_runs_status_valid  CHECK (status IN (
        'PASSED', 'FAILED', 'TIMED_OUT', 'CANCELLED', 'SKIPPED')),
    CONSTRAINT verification_runs_duration_nonneg CHECK (duration_ms >= 0)
);

CREATE INDEX verification_runs_attempt_idx ON verification_runs (attempt_id, step_index);

CREATE TABLE approvals (
    id            UUID        PRIMARY KEY,
    task_id       UUID        NOT NULL REFERENCES tasks (id) ON DELETE CASCADE,
    status        TEXT        NOT NULL,
    reason        TEXT        NOT NULL DEFAULT '',
    requested_at  TIMESTAMPTZ NOT NULL DEFAULT now(),
    decided_at    TIMESTAMPTZ,
    decided_by    TEXT        NOT NULL DEFAULT '',

    CONSTRAINT approvals_status_valid CHECK (status IN ('PENDING', 'GRANTED', 'DENIED')),
    CONSTRAINT approvals_decided_consistent CHECK (
        (status = 'PENDING' AND decided_at IS NULL) OR
        (status <> 'PENDING' AND decided_at IS NOT NULL))
);

-- At most one undecided request per task, enforced by the database so that two
-- concurrent callers cannot both open one.
CREATE UNIQUE INDEX approvals_one_pending_per_task ON approvals (task_id)
    WHERE status = 'PENDING';

CREATE INDEX approvals_task_idx ON approvals (task_id, requested_at DESC);

CREATE TABLE events (
    id          UUID        PRIMARY KEY,
    -- Total order independent of clock resolution. Two events written in the
    -- same millisecond are still strictly ordered.
    seq         BIGSERIAL   NOT NULL UNIQUE,
    task_id     UUID        NOT NULL REFERENCES tasks (id) ON DELETE CASCADE,
    attempt_id  UUID        REFERENCES task_attempts (id) ON DELETE CASCADE,
    type        TEXT        NOT NULL,
    payload     JSONB       NOT NULL DEFAULT '{}'::jsonb,
    created_at  TIMESTAMPTZ NOT NULL DEFAULT now(),

    CONSTRAINT events_type_valid CHECK (type IN (
        'task.created', 'task.ready', 'task.started', 'task.succeeded',
        'task.failed', 'task.cancelled',
        'task.worktree_created', 'task.worktree_removed', 'task.worktree_retained',
        'task.worker_started', 'task.worker_completed',
        'task.verification_started', 'task.verification_step_completed',
        'task.verification_completed',
        'task.approval_required', 'task.approval_granted', 'task.approval_denied')),
    CONSTRAINT events_payload_is_object CHECK (jsonb_typeof(payload) = 'object')
);

-- Reading one task's history in order: the primary query this table exists for.
CREATE INDEX events_task_seq_idx ON events (task_id, seq);
CREATE INDEX events_type_seq_idx ON events (type, seq DESC);

-- History must never be rewritten, so UPDATE is rejected by the database rather
-- than by convention: a future bug, a careless migration, or a manual psql
-- session cannot quietly alter what happened.
--
-- DELETE is deliberately NOT blocked. Removing a task together with its history
-- is a legitimate retention operation, and the ON DELETE CASCADE above is only
-- honest if it can actually run. Editing an event, by contrast, is never
-- legitimate: the way to correct the record is to append a new event.
CREATE FUNCTION events_reject_update() RETURNS TRIGGER AS $$
BEGIN
    RAISE EXCEPTION 'events is append-only: % is not permitted', TG_OP
        USING HINT = 'append a corrective event instead of changing an existing one';
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER events_no_update BEFORE UPDATE ON events
    FOR EACH STATEMENT EXECUTE FUNCTION events_reject_update();

-- updated_at is maintained by the database so that no write path can forget it.
CREATE FUNCTION set_updated_at() RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at := now();
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER projects_set_updated_at BEFORE UPDATE ON projects
    FOR EACH ROW EXECUTE FUNCTION set_updated_at();

CREATE TRIGGER tasks_set_updated_at BEFORE UPDATE ON tasks
    FOR EACH ROW EXECUTE FUNCTION set_updated_at();
